# K Vecinos más cercanos

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Obtención de Datos

In [2]:
dataframe = pd.read_csv('vehiculos.csv')
dataframe.head()

compactness  circularity  distance_circularity  radius_ratio  \
0         95.0         48.0                  83.0         178.0   
1         91.0         41.0                  84.0         141.0   
2        104.0         50.0                 106.0         209.0   
3         93.0         41.0                  82.0         159.0   
4         85.0         44.0                  70.0         205.0   

   pr_axis_aspect_ratio  max_length_aspect_ratio  scatter_ratio  \
0                  72.0                     10.0          162.0   
1                  57.0                      9.0          149.0   
2                  66.0                     10.0          207.0   
3                  63.0                      9.0          144.0   
4                 103.0                     52.0          149.0   

   elongatedness  pr_axis_rectangularity  max_length_rectangularity  \
0           42.0                    20.0                      159.0   
1           45.0                    19.0                      143.0   
2           32.0                    23.0                      158.0   
3           46.0                    19.0                      143.0   
4           45.0                    19.0                      144.0   

   scaled_variance_major_axis  scaled_variance_minor_axis  \
0                       176.0                       379.0   
1                       170.0                       330.0   
2                       223.0                       635.0   
3                       160.0                       309.0   
4                       241.0                       325.0   

   scaled_radius_gyration  skewness_major_axis  skewness_minor_axis  \
0                   184.0                 70.0                  6.0   
1                   158.0                 72.0                  9.0   
2                   220.0                 73.0                 14.0   
3                   127.0                 63.0                  6.0   
4                   188.0                127.0                  9.0   

   kurtosis_minor_axis  kurtosis_major_axis  hollows_ratio vehicle_class  
0                 16.0                187.0          197.0           van  
1                 14.0                189.0          199.0           van  
2                  9.0                188.0          196.0          saab  
3                 10.0                199.0          207.0           van  
4                 11.0                180.0          183.0           bus

In [3]:
dataframe['vehicle_class'].unique()

array(['van', 'saab', 'bus', 'opel'], dtype=object)

## Limpieza de Datos

In [4]:
y = dataframe['vehicle_class'] # Variable Objetivo
x = dataframe.drop('vehicle_class',axis=1) # Variables Caracteristicas

## Datos de Entrenamiento - *Datos de Pruebas*

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=45)
x_train

compactness  circularity  distance_circularity  radius_ratio  \
794         87.0         41.0                  76.0         165.0   
317         95.0         45.0                 105.0         208.0   
570        105.0         53.0                 108.0         206.0   
750         96.0         40.0                  78.0         170.0   
374         87.0         36.0                  53.0         117.0   
..           ...          ...                   ...           ...   
725         91.0         37.0                  76.0         138.0   
607         86.0         39.0                  62.0         129.0   
544         88.0         43.0                  70.0         177.0   
643         95.0         43.0                  83.0         198.0   
414         85.0         45.0                  82.0         133.0   

     pr_axis_aspect_ratio  max_length_aspect_ratio  scatter_ratio  \
794                  67.0                      7.0          148.0   
317                  64.0                     10.0          187.0   
570                  63.0                     12.0          222.0   
750                  58.0                      7.0          174.0   
374                  58.0                      4.0          118.0   
..                    ...                      ...            ...   
725                  55.0                      8.0          132.0   
607                  59.0                      6.0          116.0   
544                  74.0                     19.0          152.0   
643                  69.0                      6.0          177.0   
414                  56.0                     11.0          159.0   

     elongatedness  pr_axis_rectangularity  max_length_rectangularity  \
794           45.0                    19.0                      140.0   
317           36.0                    22.0                      150.0   
570           31.0                    25.0                      168.0   
750           38.0                    21.0                      139.0   
374           57.0                    17.0                      125.0   
..             ...                     ...                        ...   
725           51.0                    18.0                      135.0   
607           57.0                    17.0                      135.0   
544           44.0                    19.0                      143.0   
643           36.0                    21.0                      139.0   
414           43.0                    20.0                      156.0   

     scaled_variance_major_axis  scaled_variance_minor_axis  \
794                       171.0                       327.0   
317                       202.0                       520.0   
570                       226.0                       712.0   
750                       197.0                       455.0   
374                       138.0                       205.0   
..                          ...                         ...   
725                       157.0                       256.0   
607                       137.0                       203.0   
544                       180.0                       342.0   
643                       189.0                       484.0   
414                       170.0                       362.0   

     scaled_radius_gyration  skewness_major_axis  skewness_minor_axis  \
794                   152.0                 72.0                  7.0   
317                   158.0                 64.0                  7.0   
570                   201.0                 71.0                 15.0   
750                   160.0                 68.0                  3.0   
374                   138.0                 85.0                  9.0   
..                      ...                  ...                  ...   
725                   124.0                 69.0                  0.0   
607                   145.0                 64.0                  7.0   
544                   168.0                 76.0        

## Modelo de Entrenamiento

In [7]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [8]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

## Modelo de Pruebas

In [9]:
predicciones = knn.predict(x_test)
predicciones

array(['saab', 'opel', 'saab', 'opel', 'saab', 'van', 'saab', 'opel',
       'saab', 'van', 'opel', 'bus', 'van', 'opel', 'opel', 'van', 'opel',
       'saab', 'bus', 'saab', 'bus', 'bus', 'bus', 'bus', 'bus', 'bus',
       'opel', 'saab', 'van', 'bus', 'opel', 'opel', 'bus', 'saab',
       'opel', 'bus', 'van', 'bus', 'bus', 'van', 'van', 'opel', 'opel',
       'bus', 'saab', 'van', 'bus', 'bus', 'opel', 'bus', 'bus', 'saab',
       'opel', 'van', 'bus', 'saab', 'saab', 'bus', 'saab', 'opel', 'van',
       'van', 'bus', 'bus', 'saab', 'van', 'bus', 'bus', 'van', 'saab',
       'van', 'bus', 'opel', 'van', 'opel', 'van', 'saab', 'saab', 'bus',
       'bus', 'van', 'saab', 'saab', 'van', 'bus', 'bus', 'saab', 'saab',
       'saab', 'van', 'van', 'van', 'van', 'saab', 'saab', 'saab', 'saab',
       'opel', 'opel', 'saab', 'bus', 'bus', 'bus', 'saab', 'van', 'bus',
       'saab', 'saab', 'saab', 'bus', 'van', 'bus', 'opel', 'bus', 'saab',
       'saab', 'opel', 'van', 'opel', 'opel', 'bus

In [10]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, predicciones))

[[65  0  7  5]
 [ 7 24 28  6]
 [ 5 26 23  3]
 [ 2  0  2 51]]


In [11]:
print(classification_report(y_test,predicciones))

              precision    recall  f1-score   support

         bus       0.82      0.84      0.83        77
        opel       0.48      0.37      0.42        65
        saab       0.38      0.40      0.39        57
         van       0.78      0.93      0.85        55

    accuracy                           0.64       254
   macro avg       0.62      0.64      0.62       254
weighted avg       0.63      0.64      0.63       254



Despues de cierta reviciones se convierte en el **Modelo Definitivo**

In [12]:
tasa_error = []
for i in range(1,20):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(x_train, y_train)
    prediccion_i = knn.predict(x_test)
    tasa_error.append(np.mean(prediccion_i != y_test))
    
tasa_error

[0.35826771653543305,
 0.3464566929133858,
 0.3188976377952756,
 0.3228346456692913,
 0.33858267716535434,
 0.3346456692913386,
 0.3228346456692913,
 0.33858267716535434,
 0.36220472440944884,
 0.3661417322834646,
 0.35039370078740156,
 0.3661417322834646,
 0.36220472440944884,
 0.38188976377952755,
 0.35039370078740156,
 0.3661417322834646,
 0.3661417322834646,
 0.3700787401574803,
 0.3661417322834646]

In [13]:
## valores = range(1,30)
## plt.plot(valores, tasa_error, color='green', marker='o', markerfacecolor='red', markersize=8)

In [14]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)
predicciones = knn.predict(x_test)
print(classification_report(y_test,predicciones))

              precision    recall  f1-score   support

         bus       0.77      0.88      0.82        77
        opel       0.58      0.45      0.50        65
        saab       0.44      0.39      0.41        57
         van       0.82      0.98      0.89        55

    accuracy                           0.68       254
   macro avg       0.65      0.67      0.66       254
weighted avg       0.66      0.68      0.66       254

