# Bosques Aleatorios - Random Forest - Clasificación

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Obtención de Datos

In [2]:
vinos = pd.read_csv('vino.csv')
vinos.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline Wine Type  
0                          3.92   1065.0       One  
1                          3.40   1050.0       One  
2                          3.17   1185.0       One  
3                          3.45   1480.0       One  
4                          2.93    735.0       One

## Limpieza de Datos

In [3]:
x = vinos.drop('Wine Type',axis=1) # Variable Objetivo
y = vinos['Wine Type'] # Varibles caracteristicas

## Datos de Entrenamiento - *Datos de Pruebas*

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

## Modelo de Entrenamiento

In [6]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
randomforest = RandomForestClassifier(n_estimators=80)
randomforest.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=80,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

## Modelo de Pruebas

In [8]:
prediccioness = randomforest.predict(x_test)
prediccioness

array(['One', 'One', 'One', 'One', 'One', 'Three', 'Three', 'Two', 'Two',
       'Three', 'Two', 'Two', 'One', 'Three', 'One', 'Two', 'One', 'Two',
       'Three', 'Two', 'Two', 'Two', 'One', 'Two', 'One', 'Three', 'One',
       'Two', 'Two', 'Three', 'Two', 'Three', 'One', 'Two', 'Three',
       'Three', 'Two', 'Three', 'Two', 'One', 'Three', 'Two', 'Two',
       'Three', 'Two', 'Two', 'Two', 'Two', 'Two', 'Two', 'Three', 'Two',
       'Two', 'One'], dtype=object)

In [9]:
y_test

5        One
6        One
25       One
73       Two
12       One
168    Three
173    Three
124      Two
111      Two
146    Three
101      Two
90       Two
42       One
139    Three
53       One
76       Two
14       One
95       Two
161    Three
82       Two
67       Two
71       Two
19       One
109      Two
8        One
147    Three
11       One
114      Two
121      Two
159    Three
85       Two
137    Three
52       One
99       Two
145    Three
151    Three
74       Two
134    Three
97       Two
10       One
144    Three
75       Two
61       Two
170    Three
100      Two
66       Two
89       Two
112      Two
68       Two
81       Two
176    Three
72       Two
65       Two
47       One
Name: Wine Type, dtype: object

In [10]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,prediccioness))

              precision    recall  f1-score   support

         One       0.93      1.00      0.96        13
       Three       1.00      1.00      1.00        14
         Two       1.00      0.96      0.98        27

    accuracy                           0.98        54
   macro avg       0.98      0.99      0.98        54
weighted avg       0.98      0.98      0.98        54



In [11]:
print(confusion_matrix(y_test,prediccioness))

[[13  0  0]
 [ 0 14  0]
 [ 1  0 26]]


Después de cierta reviciones y convercernos los resultados y las gráficas se convierte en el **Modelo Definitivo**