# Àrboles de Decisión

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

## Obtención de Datos

In [2]:
vinos = pd.read_csv('vino.csv')
vinos.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline Wine Type  
0                          3.92   1065.0       One  
1                          3.40   1050.0       One  
2                          3.17   1185.0       One  
3                          3.45   1480.0       One  
4                          2.93    735.0       One

In [3]:
vinos['Wine Type'].unique()

array(['One', 'Two', 'Three'], dtype=object)

In [4]:
vinos['Wine Type'].value_counts()

Two      71
One      59
Three    48
Name: Wine Type, dtype: int64

## Limpieza de Datos

In [5]:
x = vinos.drop('Wine Type',axis=1) # Variable Objetivo
y = vinos['Wine Type'] # Varibles caracteristicas

## Datos de Entrenamiento - *Datos de Pruebas*

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

## Modelo de Entrenamiento

In [7]:
from sklearn.tree import DecisionTreeClassifier

In [8]:
arbol = DecisionTreeClassifier()

In [9]:
arbol.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

## Modelo de Pruebas

In [10]:
predicciones = arbol.predict(x_test)

In [11]:
predicciones

array(['One', 'Two', 'Three', 'Three', 'Two', 'Two', 'Three', 'Three',
       'Three', 'Two', 'Three', 'One', 'Two', 'One', 'One', 'Three',
       'Three', 'One', 'Two', 'Three', 'Three', 'One', 'One', 'One',
       'One', 'Two', 'Two', 'Three', 'Three', 'Three', 'One', 'Two',
       'Three', 'Three', 'One', 'Two', 'Two', 'Two', 'One', 'One', 'One',
       'Three', 'Three', 'One', 'Two', 'Two', 'One', 'Two', 'Three',
       'Three', 'Two', 'Three', 'One', 'Two'], dtype=object)

In [12]:
y_test

73       Two
115      Two
148    Three
172    Three
123      Two
100      Two
137    Three
146    Three
83       Two
128      Two
144    Three
24       One
68       Two
55       One
26       One
169    Three
156    Three
35       One
63       Two
176    Three
150    Three
51       One
36       One
57       One
46       One
108      Two
94       Two
167    Three
154    Three
153    Three
45       One
126      Two
147    Three
175    Three
1        One
114      Two
127      Two
113      Two
42       One
54       One
47       One
159    Three
173    Three
33       One
90       Two
99       Two
21       One
39       One
165    Three
92       Two
142    Three
149    Three
41       One
105      Two
Name: Wine Type, dtype: object

In [13]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, predicciones))

              precision    recall  f1-score   support

         One       0.94      0.94      0.94        17
       Three       0.90      0.95      0.92        19
         Two       0.88      0.83      0.86        18

    accuracy                           0.91        54
   macro avg       0.91      0.91      0.91        54
weighted avg       0.91      0.91      0.91        54



In [14]:
print(confusion_matrix(y_test,predicciones))

[[16  0  1]
 [ 0 18  1]
 [ 1  2 15]]


Después de cierta reviciones y convercernos los resultados y las gráficas se convierte en el **Modelo Definitivo**