# NumPy arrays - arange, zeros, ones, linspace, eye

In [1]:
import numpy as np

## Arange

In [2]:
array = np.arange(7)
array

array([0, 1, 2, 3, 4, 5, 6])

In [3]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
 np.arange(3,20,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

## Zeros

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Ones

In [7]:
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Linspace

In [9]:
np.linspace(5,8,20)

array([5.        , 5.15789474, 5.31578947, 5.47368421, 5.63157895,
       5.78947368, 5.94736842, 6.10526316, 6.26315789, 6.42105263,
       6.57894737, 6.73684211, 6.89473684, 7.05263158, 7.21052632,
       7.36842105, 7.52631579, 7.68421053, 7.84210526, 8.        ])

In [10]:
np.linspace(2,9,40)

array([2.        , 2.17948718, 2.35897436, 2.53846154, 2.71794872,
       2.8974359 , 3.07692308, 3.25641026, 3.43589744, 3.61538462,
       3.79487179, 3.97435897, 4.15384615, 4.33333333, 4.51282051,
       4.69230769, 4.87179487, 5.05128205, 5.23076923, 5.41025641,
       5.58974359, 5.76923077, 5.94871795, 6.12820513, 6.30769231,
       6.48717949, 6.66666667, 6.84615385, 7.02564103, 7.20512821,
       7.38461538, 7.56410256, 7.74358974, 7.92307692, 8.1025641 ,
       8.28205128, 8.46153846, 8.64102564, 8.82051282, 9.        ])

## Eye

In [11]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])