# NumPy arrays - Números aleatorios - Rand y Randn

In [1]:
import numpy as np

## Rand

In [2]:
np.random.rand(5) # Esto sigue una distribución uniforme

array([0.37951115, 0.71584955, 0.39352929, 0.79199568, 0.70764233])

In [3]:
np.random.rand(3,7)

array([[0.00355078, 0.52933998, 0.73807318, 0.8632471 , 0.98397921,
        0.95348755, 0.13274534],
       [0.95906441, 0.70305811, 0.90436208, 0.92721222, 0.98915983,
        0.1756786 , 0.80320769],
       [0.60131883, 0.64212776, 0.55102941, 0.36843573, 0.40513745,
        0.34543929, 0.7224818 ]])

## Randn

In [4]:
np.random.randn(5) # Esto sigue una distribución normal

array([-1.5494619 ,  0.4679994 ,  0.73790079, -0.93838384,  1.00787187])

In [5]:
np.random.randn(5,3)

array([[ 0.52000185, -0.95020737, -0.86703875],
       [-1.00225021, -2.28889115,  0.3871276 ],
       [ 0.19223128, -0.86756724,  0.47559083],
       [ 0.2741441 , -0.47708798,  0.32226697],
       [-0.77343194, -0.4649272 ,  0.04253907]])