# NumPy - Indexación en arrays

In [1]:
import numpy as np

In [2]:
array = np.arange(1,17)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [3]:
array[5]

6

In [4]:
array[-1] # Obten el último elemento del array

16

In [5]:
array[5:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [6]:
array[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
array[3:8]

array([4, 5, 6, 7, 8])

In [8]:
array[2] = 100
array

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16])