# NumPy - Indexación en arrays de 2 o más dimensiones

In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
array[0]

array([1, 2, 3])

In [4]:
array[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
array2 = array[:2]
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
array[0,1]

2

In [7]:
array[0][1]

2

In [8]:
array[2,1]

8

In [9]:
array[:,0]

array([1, 4, 7])

In [10]:
array[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])