# NumPy - Seleccionar elementos de un array según una condición

In [1]:
import numpy as np

In [2]:
array = np.arange(1,14)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [3]:
condicion = array > 6
condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True])

In [4]:
array[condicion]

array([ 7,  8,  9, 10, 11, 12, 13])

In [5]:
array6 = array[condicion]

In [6]:
array6

array([ 7,  8,  9, 10, 11, 12, 13])

In [7]:
array[array % 2 == 0]
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [8]:
array[array % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])