# NumPy - Operaciones sobre los arrays

In [1]:
import numpy as np
array = np.arange(1,12)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
array + array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [3]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
array * 100

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000, 1100])

In [5]:
array + 25

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36])

In [6]:
array - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [7]:
array2 = np.arange(5,16)
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
array * array2 # Los arreglos deben ser del mismo tamaño

array([  5,  12,  21,  32,  45,  60,  77,  96, 117, 140, 165])

In [9]:
np.sqrt(array2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [10]:
np.max(array)

11

In [11]:
np.min(array2)

5